services:
  age-db:
    image: apache/age:latest
    container_name: age_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bimatlas
      POSTGRES_PASSWORD: bimatlas
      POSTGRES_DB: bimatlas
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init-age.sql:/docker-entrypoint-initdb.d/init-age.sql

volumes:
  pgdata: